server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': 
            allowed-origins: "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
            allow-credentials: true 

      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/signup, /api/users/login , /api/users/logout , , /api/users/refresh
          filters:
            - StripPrefix=1 


        - id: user-service-private
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/me/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter 

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter 

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter 

# JWT 검증을 위한 비밀키 설정 (user-service와 동일해야 함)
jwt:
  secret: V293aG9hbnNbamVvbmduYWUgY2hhbmdlIHNpbXNpbWhhZGEK

logging:
  level:
    org.springframework.security: DEBUG