server:
  port: 8000

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': 
            allowed-origins: "http://localhost:5173" 
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE 
          predicates:
            - Path=/api/products/**