eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# --- docker 프로필용 설정 ---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/