server:
  port: 8083 

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/service_order
    username: erp
    password: wein123!
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: kafka:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer