server:
  port: 8082

jwt:
  secret: V293aG9hbnNbamVvbmduYWUgY2hhbmdlIHNpbXNpbWhhZGEK # Base64 인코딩된 문자열
   # Access Token 유효기간 (1시간)
  access-token-validity-in-seconds: 3600
  # Refresh Token 유효기간 (7일)
  refresh-token-validity-in-seconds: 604800

logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecoms_user
    username: erp
    password: wein123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgresql:5432/ecoms_user
  data:
    redis:
      host: redis

